# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: poke.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='poke.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\npoke.proto\" \n\rRequestHeader\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"7\n\x05Model\x12\x15\n\rclient_health\x18\x01 \x01(\x05\x12\x17\n\x0fopponent_health\x18\x02 \x01(\x05\"1\n\x0fGetModelRequest\x12\x1e\n\x06header\x18\x01 \x01(\x0b\x32\x0e.RequestHeader\"&\n\rGetModelReply\x12\x15\n\x05model\x18\x01 \x01(\x0b\x32\x06.Model\"\x06\n\x04Move\"R\n\x0e\x43ommandRequest\x12\x1e\n\x06header\x18\x01 \x01(\x0b\x32\x0e.RequestHeader\x12\x15\n\x04move\x18\x02 \x01(\x0b\x32\x05.MoveH\x00\x42\t\n\x07\x63ommand\"$\n\x0c\x43ommandReply\x12\x14\n\x04\x64iff\x18\x01 \x01(\x0b\x32\x06.Model\"-\n\x0bWaitRequest\x12\x1e\n\x06header\x18\x01 \x01(\x0b\x32\x0e.RequestHeader\"!\n\tWaitReply\x12\x14\n\x04\x64iff\x18\x01 \x01(\x0b\x32\x06.Model2\x87\x01\n\x04Poke\x12.\n\x08GetModel\x12\x10.GetModelRequest\x1a\x0e.GetModelReply\"\x00\x12+\n\x07\x43ommand\x12\x0f.CommandRequest\x1a\r.CommandReply\"\x00\x12\"\n\x04Wait\x12\x0c.WaitRequest\x1a\n.WaitReply\"\x00\x62\x06proto3'
)




_REQUESTHEADER = _descriptor.Descriptor(
  name='RequestHeader',
  full_name='RequestHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='RequestHeader.user_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=46,
)


_MODEL = _descriptor.Descriptor(
  name='Model',
  full_name='Model',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_health', full_name='Model.client_health', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='opponent_health', full_name='Model.opponent_health', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=103,
)


_GETMODELREQUEST = _descriptor.Descriptor(
  name='GetModelRequest',
  full_name='GetModelRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='GetModelRequest.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=154,
)


_GETMODELREPLY = _descriptor.Descriptor(
  name='GetModelReply',
  full_name='GetModelReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='model', full_name='GetModelReply.model', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=194,
)


_MOVE = _descriptor.Descriptor(
  name='Move',
  full_name='Move',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=196,
  serialized_end=202,
)


_COMMANDREQUEST = _descriptor.Descriptor(
  name='CommandRequest',
  full_name='CommandRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='CommandRequest.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='move', full_name='CommandRequest.move', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='command', full_name='CommandRequest.command',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=204,
  serialized_end=286,
)


_COMMANDREPLY = _descriptor.Descriptor(
  name='CommandReply',
  full_name='CommandReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='diff', full_name='CommandReply.diff', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=288,
  serialized_end=324,
)


_WAITREQUEST = _descriptor.Descriptor(
  name='WaitRequest',
  full_name='WaitRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='WaitRequest.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=326,
  serialized_end=371,
)


_WAITREPLY = _descriptor.Descriptor(
  name='WaitReply',
  full_name='WaitReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='diff', full_name='WaitReply.diff', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=373,
  serialized_end=406,
)

_GETMODELREQUEST.fields_by_name['header'].message_type = _REQUESTHEADER
_GETMODELREPLY.fields_by_name['model'].message_type = _MODEL
_COMMANDREQUEST.fields_by_name['header'].message_type = _REQUESTHEADER
_COMMANDREQUEST.fields_by_name['move'].message_type = _MOVE
_COMMANDREQUEST.oneofs_by_name['command'].fields.append(
  _COMMANDREQUEST.fields_by_name['move'])
_COMMANDREQUEST.fields_by_name['move'].containing_oneof = _COMMANDREQUEST.oneofs_by_name['command']
_COMMANDREPLY.fields_by_name['diff'].message_type = _MODEL
_WAITREQUEST.fields_by_name['header'].message_type = _REQUESTHEADER
_WAITREPLY.fields_by_name['diff'].message_type = _MODEL
DESCRIPTOR.message_types_by_name['RequestHeader'] = _REQUESTHEADER
DESCRIPTOR.message_types_by_name['Model'] = _MODEL
DESCRIPTOR.message_types_by_name['GetModelRequest'] = _GETMODELREQUEST
DESCRIPTOR.message_types_by_name['GetModelReply'] = _GETMODELREPLY
DESCRIPTOR.message_types_by_name['Move'] = _MOVE
DESCRIPTOR.message_types_by_name['CommandRequest'] = _COMMANDREQUEST
DESCRIPTOR.message_types_by_name['CommandReply'] = _COMMANDREPLY
DESCRIPTOR.message_types_by_name['WaitRequest'] = _WAITREQUEST
DESCRIPTOR.message_types_by_name['WaitReply'] = _WAITREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestHeader = _reflection.GeneratedProtocolMessageType('RequestHeader', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTHEADER,
  '__module__' : 'poke_pb2'
  # @@protoc_insertion_point(class_scope:RequestHeader)
  })
_sym_db.RegisterMessage(RequestHeader)

Model = _reflection.GeneratedProtocolMessageType('Model', (_message.Message,), {
  'DESCRIPTOR' : _MODEL,
  '__module__' : 'poke_pb2'
  # @@protoc_insertion_point(class_scope:Model)
  })
_sym_db.RegisterMessage(Model)

GetModelRequest = _reflection.GeneratedProtocolMessageType('GetModelRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETMODELREQUEST,
  '__module__' : 'poke_pb2'
  # @@protoc_insertion_point(class_scope:GetModelRequest)
  })
_sym_db.RegisterMessage(GetModelRequest)

GetModelReply = _reflection.GeneratedProtocolMessageType('GetModelReply', (_message.Message,), {
  'DESCRIPTOR' : _GETMODELREPLY,
  '__module__' : 'poke_pb2'
  # @@protoc_insertion_point(class_scope:GetModelReply)
  })
_sym_db.RegisterMessage(GetModelReply)

Move = _reflection.GeneratedProtocolMessageType('Move', (_message.Message,), {
  'DESCRIPTOR' : _MOVE,
  '__module__' : 'poke_pb2'
  # @@protoc_insertion_point(class_scope:Move)
  })
_sym_db.RegisterMessage(Move)

CommandRequest = _reflection.GeneratedProtocolMessageType('CommandRequest', (_message.Message,), {
  'DESCRIPTOR' : _COMMANDREQUEST,
  '__module__' : 'poke_pb2'
  # @@protoc_insertion_point(class_scope:CommandRequest)
  })
_sym_db.RegisterMessage(CommandRequest)

CommandReply = _reflection.GeneratedProtocolMessageType('CommandReply', (_message.Message,), {
  'DESCRIPTOR' : _COMMANDREPLY,
  '__module__' : 'poke_pb2'
  # @@protoc_insertion_point(class_scope:CommandReply)
  })
_sym_db.RegisterMessage(CommandReply)

WaitRequest = _reflection.GeneratedProtocolMessageType('WaitRequest', (_message.Message,), {
  'DESCRIPTOR' : _WAITREQUEST,
  '__module__' : 'poke_pb2'
  # @@protoc_insertion_point(class_scope:WaitRequest)
  })
_sym_db.RegisterMessage(WaitRequest)

WaitReply = _reflection.GeneratedProtocolMessageType('WaitReply', (_message.Message,), {
  'DESCRIPTOR' : _WAITREPLY,
  '__module__' : 'poke_pb2'
  # @@protoc_insertion_point(class_scope:WaitReply)
  })
_sym_db.RegisterMessage(WaitReply)



_POKE = _descriptor.ServiceDescriptor(
  name='Poke',
  full_name='Poke',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=409,
  serialized_end=544,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetModel',
    full_name='Poke.GetModel',
    index=0,
    containing_service=None,
    input_type=_GETMODELREQUEST,
    output_type=_GETMODELREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Command',
    full_name='Poke.Command',
    index=1,
    containing_service=None,
    input_type=_COMMANDREQUEST,
    output_type=_COMMANDREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Wait',
    full_name='Poke.Wait',
    index=2,
    containing_service=None,
    input_type=_WAITREQUEST,
    output_type=_WAITREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_POKE)

DESCRIPTOR.services_by_name['Poke'] = _POKE

# @@protoc_insertion_point(module_scope)
